from typing import Protocol


class VectorStore(Protocol):
    def ensure_collection(self, name: str) -> None: ...
    def list_collections(self) -> list[str]: ...
    def upsert_chunks(
        self,
        collection: str,
        ids: list[str],
        texts: list[str],
        embeddings: list[list[float]],
        metadatas: list[dict],
    ) -> None: ...
    def query_chunks(self, collection: str, embedding: list[float], n_results: int = 5) -> list[dict]: ...
    def get_chunks_by_ids(self, collection: str, ids: list[str]) -> list[dict]: ...
    def delete_chunks(self, collection: str, where: dict) -> None: ...
    def delete_collection(self, name: str) -> None: ...
    def close(self) -> None: ...
